version: '3'
services:
  redis-server:
    image: 'redis'
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  db-app:
    build: ./
    ports:
      - "3000:3000"
